### ISSUE TITLE
Template paths are outdated

### ISSUE THREAD

**Issue by kadamwhite** [humanmade/chassis_aws_analytics#7]
Looking at [cogito.service](https://github.com/humanmade/chassis_aws_analytics/blob/master/modules/chassis_aws_analytics/templates/cognito.service#L9) and [pinpoint.service](https://github.com/humanmade/chassis_aws_analytics/blob/master/modules/chassis_aws_analytics/templates/pinpoint.service#L9) in the templates folder, I see outdated paths with the dashes instead of underscores:

- WorkingDirectory=/vagrant/extensions/chassis-aws-analytics/local-cognito/
- WorkingDirectory=/vagrant/extensions/chassis-aws-analytics/local-pinpoint/

I assume we should update these in light of #4

**Comment by roborourke** [comment]
🤦‍♂
